// Code generated by GoVPP's binapi-generator. DO NOT EDIT.

package cup_ipfilter

import (
	"context"

	api "git.fd.io/govpp.git/api"
)

// RPCService defines RPC service cup_ipfilter.
type RPCService interface {
	CupAddIPFilterPol(ctx context.Context, in *CupAddIPFilterPol) (*CupAddIPFilterPolReply, error)
	CupDelIPFilterPol(ctx context.Context, in *CupDelIPFilterPol) (*CupDelIPFilterPolReply, error)
}

type serviceClient struct {
	conn api.Connection
}

func NewServiceClient(conn api.Connection) RPCService {
	return &serviceClient{conn}
}

func (c *serviceClient) CupAddIPFilterPol(ctx context.Context, in *CupAddIPFilterPol) (*CupAddIPFilterPolReply, error) {
	out := new(CupAddIPFilterPolReply)
	err := c.conn.Invoke(ctx, in, out)
	if err != nil {
		return nil, err
	}
	return out, api.RetvalToVPPApiError(out.Retval)
}

func (c *serviceClient) CupDelIPFilterPol(ctx context.Context, in *CupDelIPFilterPol) (*CupDelIPFilterPolReply, error) {
	out := new(CupDelIPFilterPolReply)
	err := c.conn.Invoke(ctx, in, out)
	if err != nil {
		return nil, err
	}
	return out, api.RetvalToVPPApiError(out.Retval)
}
