// Code generated by GoVPP's binapi-generator. DO NOT EDIT.

package cup_handoff

import (
	"context"

	api "go.fd.io/govpp/api"
)

// RPCService defines RPC service cup_handoff.
type RPCService interface {
	CupSetOutputs(ctx context.Context, in *CupSetOutputs) (*CupSetOutputsReply, error)
	CupSetWorkers(ctx context.Context, in *CupSetWorkers) (*CupSetWorkersReply, error)
}

type serviceClient struct {
	conn api.Connection
}

func NewServiceClient(conn api.Connection) RPCService {
	return &serviceClient{conn}
}

func (c *serviceClient) CupSetOutputs(ctx context.Context, in *CupSetOutputs) (*CupSetOutputsReply, error) {
	out := new(CupSetOutputsReply)
	err := c.conn.Invoke(ctx, in, out)
	if err != nil {
		return nil, err
	}
	return out, api.RetvalToVPPApiError(out.Retval)
}

func (c *serviceClient) CupSetWorkers(ctx context.Context, in *CupSetWorkers) (*CupSetWorkersReply, error) {
	out := new(CupSetWorkersReply)
	err := c.conn.Invoke(ctx, in, out)
	if err != nil {
		return nil, err
	}
	return out, api.RetvalToVPPApiError(out.Retval)
}
